### ISSUE TITLE
Unable to rotate DNS challenges: 'record'

### ISSUE THREAD

**Issue by HappyRogue658** [aaomidi/certbot-dns-google-domains#33]
Hi, even though this works, and I do get a certificate, I am also getting an error "Unable to rotate DNS challenges: 'record'"

However, there does not seem to be a residual record "_acme-challenge.domain.com" left.

What does this mean?

I am including a partial shell output/log file

[certbot error.txt](https://github.com/aaomidi/certbot-dns-google-domains/files/11260019/certbot.error.txt)

**Comment by vg** [comment]
looks like Google Domains only keeps those _acme-challenge.domain.com TXT records for a short duration.

**Comment by aready87** [comment]
Hello,

I also got the same error even though I received my certificate.

```
Waiting 30 seconds for DNS changes to propagate
Encountered exception during recovery: certbot.errors.PluginError: Unable to rotate DNS challenges: 'record'

Successfully received certificate.
```

**Comment by santanaluiz** [comment]
+1

**Comment by bernhard-kohl** [comment]
Hi, I just started to use certbot-dns-google-domains for my new google-domain and got the same error, but the certificate was successfully received. Could you please release this fix to PyPi! Thank You.
